#!/bin/bash

# Required variables: COOKIE, DIST_MIN, DIST_MAX

set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

NODENAME=$2

PATH=/var/vcap/packages/service_agent/erts-6.3/bin:$PATH
LOGFILE=/var/vcap/sys/log/erlang/${NODENAME}.log
COOKIE_FLAG="-setcookie $COOKIE"
DIST_FLAG="-kernel inet_dist_listen_min $DIST_MIN -kernel inet_dist_listen_max $DIST_MAX"
LOG_FLAG="-boot start_sasl -sasl sasl_error_logger {file,\"$LOGFILE\"}"
DAEMON_FLAG="-detached -heart -noshell"
STOPCMD="rpc:call('${NODENAME}@${BIND_ADDR}', init, stop, [])"

export LANG=en_US.UTF-8

case $1 in

  start)
    erl -name $NODENAME@$BIND_ADDR $LOG_FLAG \
      $COOKIE_FLAG $DAEMON_FLAG $DIST_FLAG
    ;;

  stop)
    erl -noshell -name erlang_ctl@127.0.0.1 $COOKIE_FLAG \
       -eval "$STOPCMD" -s init stop
    ;;
  *)
    echo "Usage: BIND_ADDR=<addr> COOKIE=<cookie> DIST_MIN=<min> DIST_MAX=<max> instance_ctl {start|stop} <instance name>"

    ;;

esac
echo ok
exit 0